Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolarCape.Models
{
    public class Project
    {
        [Key]
        [Required]
        public int ProjectId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }

        [Required]
        [Display(Name = "End Date")]
        public DateTime EndDate { get; set; }

        public IEnumerable<SelectListItem> Client { get; set; }

        public virtual ICollection<Client> Clients { get; set; }

        public IEnumerable<SelectListItem> Employee { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
    }
}

Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PolarCape.Data;
using PolarCape.Models;

namespace PolarCape.Controllers
{
    public class ClientsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Clients
        public ActionResult Index()
        {
            return View(db.Clients.ToList());
        }

        // GET: Clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClientId,Name,PhoneNumber,Email,Company")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(client);
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClientId,Name,PhoneNumber,Email,Company")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PolarCape.Data;
using PolarCape.Models;

namespace PolarCape.Controllers
{
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Projects
        public ActionResult Index()
        {
            return View(db.Projects.ToList());
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectId,Name,StartDate,EndDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projects.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProjectId,Name,StartDate,EndDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        public ActionResult InsertProject(int id)
        {
            ProjectClientEmployee model = new ProjectClientEmployee();
            model.ProjectId = id;
            model.Client = db.Clients.ToList();
            model.Employees = db.Employees.ToList();
            model.Project = db.Projects.Find(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult InsertProject(ProjectClientEmployee model)
        {
            var project = db.Projects.Find(model.ProjectId);
            var client = db.Clients.Find(model.ClientId);
            var employee = db.Employees.Find(model.EmployeeId);
            project.Clients.Add(client);
            project.Employees.Add(employee);
            db.SaveChanges();
            return View("Index", db.Projects.ToList());
        }


        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Projects/Create.cshtml
@model PolarCape.Models.Project

@{
    ViewBag.Title = "Create";
}

<h3>Create new project</h3>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-success" />
            @Html.ActionLink("Back to List", "Index", "Projects", new { @class = "btn btn-default" })
        </div>
    </div>

</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Projects/Delete.cshtml
@model PolarCape.Models.Project

@{
    ViewBag.Title = "Delete";
}



<h3>Are you sure you want to delete the project @Model.Name?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            @Html.ActionLink("Back to List", "Index", "Projects", new { @class = "btn btn-default"})
        </div>
    }
</div>

Views/Projects/Details.cshtml
@model PolarCape.Models.Project

@{
    ViewBag.Title = "Details";
}

<div>
    <h3>Details on @Model.Name</h3>
    <hr />
    <div>
        <div class="row">
            <div class="col-md-2">
                @Html.DisplayNameFor(model => model.Name)
            </div>
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Name)
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                @Html.DisplayNameFor(model => model.StartDate)
            </div>
            <div class="col-md-10">
                @Html.DisplayFor(model => model.StartDate)
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                @Html.DisplayNameFor(model => model.EndDate)
            </div>
            <div class="col-md-10">
                @Html.DisplayFor(model => model.EndDate)
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <b>Client: </b>
            </div>
            <div class="col-md-10">
                <ul style="list-style-type:none">
                    @foreach (var client in Model.Clients)
                    {
                        <li>
                            <a href="/Clients/Details/@client.ClientId" style="color:black">@client.Name</a>
                        </li>
                    }
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <b>Employees: </b>
            </div>
            <div class="col-md-10">
                <ul style="list-style-type:none">
                    @foreach (var employee in Model.Employees)
                    {
                        <li>
                            <a href="/Clients/Details/@employee.EmployeeId" style="color:black">@employee.Name</a>
                        </li>
                    }
                </ul>
            </div>
        </div>

    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", "Index", new { id = Model.ProjectId }, new { @class = "btn btn-primary"}) 
    @Html.ActionLink("Back to List", "Index", "Projects", new { @class = "btn btn-default"})
</p>

Views/Projects/Edit.cshtml
@model PolarCape.Models.Project

@{
    ViewBag.Title = "Edit";
}

<h3>Edit the project @Model.Name</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProjectId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                @Html.ActionLink("Back to List", "Index", "Projects", new { @class = "btn btn-default"})
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Projects/Index.cshtml
@model IEnumerable<PolarCape.Models.Project>

@{
    ViewBag.Title = "Index";
}

<h3>Projects</h3>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.ActionLink("Client and employees", "InsertProject", "Projects", new { id = item.ProjectId }, new { @class = "btn btn-primary"}) 
            @Html.ActionLink("Edit", "Edit", "Projects", new { id = item.ProjectId }, new { @class = "btn btn-primary" }) 
            @Html.ActionLink("Details", "Details", "Projects", new { id = item.ProjectId }, new { @class = "btn btn-success" }) 
            @Html.ActionLink("Delete", "Delete", "Projects", new { id = item.ProjectId }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

<p style="text-align:right">
    @Html.ActionLink("Create New", "Create", "Projects", new { @class = "btn btn-primary" })
</p>

Views/Projects/InsertProject.cshtml
@model PolarCape.Models.ProjectClientEmployee

@{
    ViewBag.Title = "InsertProject";
}



@using (Html.BeginForm("InsertProject", "Projects"))
{
    <h3>Pick a client and employee for @Model.Project.Name</h3>
    <hr />
    <div class="form-group">
        @Html.HiddenFor(model => model.ProjectId)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Client, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.DropDownListFor(model => model.ClientId, new SelectList(Model.Client, "ClientId", "Name"), new { @class = "form-control" })
            @Html.HiddenFor(model => model.ClientId)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Employees, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.DropDownListFor(model => model.EmployeeId, new SelectList(Model.Employees, "EmployeeId", "Name"), new { @class = "form-control" })
            @Html.HiddenFor(model => model.EmployeeId)
        </div>
    </div>
    <br />

    <div class="form-group">
        <br />
        <br />
        <button type="submit" class="btn btn-success">Choose</button>
        @Html.ActionLink("Cancel", "Index", "Clients", new { @class = "btn btn-default" })

    </div>
}